server:
  port: 9999
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/delivery?serverTimezone=UTC&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效
mybatis-plus:
  mapper-locations: classpath:mapping/*.xml
  typeAliasesPackage: com.delivery.main.common.persistence.template.modal
#  servlet:
#    multipart:
#      # 文件传输大小最大值设置
#      max-file-size: 2Mb
#      max-request-size: 100Mb


